var data = [
    ["How many standard Rubik's Cubes would fit in the Atlantic Ocean?",21],
    ["What does General Sherman (a sequoia tree and the world's largest tree) weigh, measured in units of US dollar coins?",9],
    ["How many ping pong balls are needed to blanket the surface area of an Olympic-sized swimming pool?",6],
    ["Your chance of winning the lottery is one in 100 million. If you stacked up all of this different lottery tickets, how tall would this stack be?",4],
    ["How many airplane flights do Canadians take in one year",7],
    ["If all the humans in the world were crammed together, how much area would we require? Answer in meter squared",12],
    ["How many golf balls would it take to circle the Earth at the equator?", 9],
    ["If all the pickles sold in the US last year were placed end-to-end, what distance would they cover? Answer in meters", 8],
    ["What is the surface area of a typical bath towel (include the fibers!) Compare this to the area of a room, a house, a football field. Answer in meter squared", 2],
    ["How much domestic trash is collected each year in the US. Answer in kilograms",10],
    ["On average, how many people are airborne over the US at any given moment?", 5],
    ["How many cells are there in the human body?", 14],
    ["What is the total volume of human blood in the world? Answer in meter cubed", 9],
    ["How long a hot dog can be made from a typical cow?", 2],
    ["How far does a soccer player travel during the course of a 90-minute game?", 4],
    ["How many people in the world are picking their nose right now?", 7],
    ["2 million people responded to storm area 51. If they all showed up, how many porta-potties is needed?", 4],
    ["How many total kilometers do all Canadians drive in one year?",11],
    ["How much total extra time would Canadians spend driving each year if we lowered the highway speed limit from 100 to 90 km/h? Answer in lifetimes.",2],
    ["Probability of dying in a large airplane per km travelled divided by probability of dying in a car per km travelled", -3],
    ["Probability of getting killed by a shark at the beach divided by probability of dying driving to the beach", -2],
    ["On average, how much does each cigarette smoked by a heavy smoker shorten his or her life expectancy? Answer in minutes", 1],
    ["What is the height of Salto Angel (the world's largest waterfall), as a multiple of the height of Mount Everest?",-1],
    ["What is the volume of air that I breathe in one day? Answer in liters.",3],
    ["How many kernels of popcorn would it take to fill this classroom?",8]
]